---
- name: "show remote environment"
  shell: env

- name: "copy backend archives"
  become: yes
  synchronize:
    src: ../../
    dest: /home/ubuntu/uda_app
    recursive: true

  # - name: "copy node_modules"
  #   become: yes
  #   synchronize:
  #     src: ../../backend/node_modules
  #     dest: /home/ubuntu/uda_app
  #     recursive: true
- name: Extract Artifact
  shell: |
    tar xzvf artifact.tar.gz
  args:
      chdir: /home/ubuntu/uda_app 

- name: "stop previous app"
  become: true
  shell: |
    pm2 stop default

- name: "start app"
  become: true
  command: |
    pm2 start -f ./main.js
  args:
      chdir: /home/ubuntu/uda_app/artifact/dist
