---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Zip Artifact
  shell: |
    cd backend
    npm i
    npm run build
    cd ..
    tar -C backend -czvf artifact.tar.gz .
    cd .circleci/ansible
    echo "Contents  of the inventory.txt file is -------"
    cat inventory.txt

- name: Starting App
  shell: |
    pm2 stop default
    pm2 start npm -- start