---
- name: Extract Artifact
  shell: |
    tar xzvf artifact.tar.gz

- name: cd artifact dir
  shell: |
    cd artifact

- name: "stop previous app"
  become: true
  shell: |
    pm2 stop default

- name: "start app"
  become: true
  command: |
    pm2 start -f ./main.js
  args:
      chdir: /home/ubuntu/dist
